### ISSUE TITLE
Error in TFS scan log however still goes to the Hub

### ISSUE THREAD

**Issue by shrewbies** [blackducksoftware/hub-tfs#1]
Customer:
We have been having problems with the Black Duck CLI since the upgrade.  We are using v3.4.1.
The CLI does seem to work, in that it creates the json file, and posts it to BlackDuck.  However, it fails afterward.  “ERROR: Unknown error.”
The CLI is being run by your TFS task.  Note that the build task is not set to fail on policy violations.

[cli-output.zip](https://github.com/blackducksoftware/hub-tfs/files/657978/cli-output.zip)
[tfs-logs.zip](https://github.com/blackducksoftware/hub-tfs/files/657979/tfs-logs.zip)

Support:
The specific message is the 2016-12-15T20:03:36.6145112Z ##[error]ERROR: Unknown error.
Essentially they see an error on the build but the project built out the full BOM on the Hub server

Sean Graham
Technical Support Engineer
Black Duck Software

**Comment by bgeveritt** [comment]
With Hub 3.4, new error messages were added. The plugin needed to be updated to factor these in. As of this writing, when using any Hub instance 3.4+, please use hub-tfs v0.5.0
