### ISSUE TITLE
Support to exclude specific directories while running a scan using the Hub TFS plugin

### ISSUE THREAD

**Issue by utsavsanghani** [blackducksoftware/hub-tfs#2]
The Hub supports excluding specific directories while trying to scan using the command line. Replicating that functionality in TFS

**Comment by bgeveritt** [comment]
The plugin already excludes a directory ("$tf") that TFS creates by default in local workspaces. It can get quite large, so the decision to ignore it via the "-exclude" flag was made when it became available in Hub 3.3.0. With that said, further exclude functionality can be accomplished with the current plugin version; as long as a ".bdignore" file is included in the scan target, it will be respected.

**Comment by utsavsanghani** [comment]
Great. Thanks @bgeveritt
