### ISSUE TITLE
2.1.4 breaks existing systems with new dependency upon Java

### ISSUE THREAD

**Issue by daughey** [blackducksoftware/hub-tfs#4]
Hi,

The latest update 2.1.4 has just caused my scan jobs to stop working.  
[4_Execute a Black Duck Hub scan against your build .log](https://github.com/blackducksoftware/hub-tfs/files/1647189/4_Execute.a.Black.Duck.Hub.scan.against.your.build.log)

Upon closer investigation I found out it was because 2.1.4 now depends upon Java.
![image](https://user-images.githubusercontent.com/19322469/35160120-27074e0e-fd34-11e7-96ed-e9b9c7817c30.png)

I think the new dependency is unreasonable as it expects all users to change their TFS build farms to have a new dependency on Java just for this.

The changes look like they're for importing SSL certificates into the machine's certificate store.  There are other ways of doing this without Java.  Perhaps PowerShell's Import-Certificate cmdlet would be more appropriate?

I recommend reverting to 2.1.3 until this is resolved.

Thanks,
Dave

**Comment by bgeveritt** [comment]
Hi David -

We'll investigate an alternate method, namely the Import-Certificate cmdlet, and hope to provide a quick turnaround. In the interim, 2.1.3 is available from the releases page:

https://github.com/blackducksoftware/hub-tfs/releases

**Comment by bgeveritt** [comment]
Hi David -

Version 2.2.0 has been published to the Visual Studio Marketplace and the GitHub releases page. It is no longer dependent upon Java being installed on the machine. Thanks for submitting an issue (and providing clear details and logs) - much appreciated!

Bailey

**Comment by daughey** [comment]
Excellent!  Thank you for the fast turn around!
